language: julia
os:
    - linux
julia:
    - 0.5

notifications:
    email: false
git:
  depth: 999999

before_install:
    - pwd
    - openssl aes-256-cbc -K $encrypted_44514ba1fcac_key -iv $encrypted_44514ba1fcac_iv -in .google_credentials.json.enc -out ../../../.google_credentials.json -d

script:
    - julia -e 'Pkg.clone(pwd()); Pkg.test("GSDicts")'
